### ISSUE TITLE
pnpm should default to --ignore-scripts and --no-frozen-lockfile when installing

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-try#993]
--no-frozen-lockfile or --no-lockfile, (I think already doing), obvious, we're changing deps (noted because when you set buildManagerOptions, you override)
--ignore-scripts, because folks who use `prepare` _and_ use typescript will have a failing build. we do not want to re-build the addon during ember-try's install.

for example, if someone is relying on `prepare` behavior to build their addon:
```yml
  try-scenarios:
    timeout-minutes: 10
    name: "Try: ${{ matrix.ember-try-scenario }}"
    runs-on: ubuntu-latest

    strategy:
      # ...
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
      # with prepare the addon builds with correct types, deps, etc
      - run: pnpm install 
      # however, today, with prepare, ember-try rebuilds it, but with incorrect dependencies (due to the ember-try config)
      # and potential repo-configurations to get around peer problems
      # such as public-hoist-pattern=ember-source
      - working-directory: test-app
        run: node_modules/.bin/ember try:one ${{ matrix.ember-try-scenario }} --skip-cleanup
```
